# Generated by Django 5.1.3 on 2024-11-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_reserva_status_alter_reserva_data_reserva_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
