# Generated by Django 5.2.8 on 2025-11-10 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_remove_reserva_status_reserva_notificado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=128)),
                ('nivel_acesso', models.IntegerField(choices=[(1, 'Geral'), (2, 'Superadmin')], default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='devolvido',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='notificado',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='livro',
            name='ano_publicacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_disponivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='ativa', max_length=20),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
